---
title: "Final Project"
author: "Alison and Walter"
date: 2020-12-4
output:
  github_document:
    toc: true
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE}
library(tidyverse)
library(readxl)
```

# Details on the datasets  

<!-- -------------------------------------------------- -->

### Spotify dataset: 
To read the csv of the song geature data data, use this code:

```{r read-feature}
filename_feature <- "./data/Song_Features.xlsx"
df_feature <- read_excel(filename_feature)
df_feature
```

### Billboard dataset: 
To read the excel of the Billboard data, use this code:

```{r read-billboard}
filename_billboard <- "./data/billboard_data.csv"
df_billboard <- read_csv(filename_billboard)
df_billboard

```

### Join Datasets
The following code joins the two datasets by song title

```{r}
df_combined_data <-
  inner_join(df_feature, df_billboard, by = "SongID")

##Change all the variable names
df_data <-df_combined_data %>%
  mutate(
    week_position = df_combined_data$'Week Position',
    prev_week_pos = df_combined_data$'Previous Week Position',
    peak_position = df_combined_data$'Peak Position',
    weeks_on_chart = df_combined_data$'Weeks on Chart'
    ) %>%
  select(-c(
    'Week Position',
    'Weeks on Chart',
    'Previous Week Position',
    'Peak Position',
    'url',
    'spotify_track_preview_url',
    'spotify_track_id'
    ))
df_data %>% summary

```


```{r - basic EDA}
df_data %>% 
  arrange(desc(peak_position)) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = peak_position, y = week_position, color = weeks_on_chart)) +
  labs(
    x = "Maximum Position on Billboard Charts",
    y = "Where the song is on the chart"
    
  )
  
```
```{r}
df_data %>% 
  filter(year == 2010) %>%
  arrange(desc(week_position))%>%
  ggplot() + 
  geom_point(mapping = aes(x = bpm, y = week_position, color = genre))

```
```{r}

```

