---
title: "Final Project"
author: "Alison and Walter"
date: 2020-12-4
output:
  github_document:
    toc: true
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE}
library(tidyverse)
library(readxl)
```

# Details on the datasets  

<!-- -------------------------------------------------- -->

```{r - tidydata}
filename <- "./data/df_data.csv"
df_data <- read_csv(filename)
df_data
```

```{r - basic EDA}
df_data %>% 
  arrange(desc(peak_position)) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = peak_position, y = week_position, color = weeks_on_chart))
  
```


```{r}
df_data %>% 
  filter(weeks_on_chart==1) %>%
  arrange(desc(week_position))%>%
  ggplot() + 
  geom_point(mapping = aes(x = bpm, y = week_position, color = genre))
  
```
```{r}
df_data %>% 
  filter(week_position == 1) %>% 
  filter(year == 2010) %>% 
  ggplot() +
  geom_point(mapping = aes(x = title, y = weeks_on_chart, color = genre)) + 
  labs(
    title = "Weeks on Chart vs. Genre for top songs in 2010"
  ) + 
  xlab("Song Title") + 
  ylab("Number of Weeks on Chart") + 
  coord_flip()
```
```{r}
df_data %>% 
  filter(week_position == 1) %>% 
  filter(year == 2010) %>% 
  ggplot() +
  geom_point(mapping = aes(x = title, y = Instance, color = genre)) + 
  labs(
    title = "Weeks on Chart vs. Genre for top songs in 2010"
  ) + 
  xlab("Song Title") + 
  ylab("Instance") + 
  coord_flip()
```

```{r}
df_data %>% 
  filter(year == 2018)
```

